services:
  - type: web
    name: jennyos-backend
    env: node
    plan: free
    rootDir: backend
    buildFilter:
      paths:
        - "backend/**"
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
